name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Android
      uses: android-actions/setup-android@v3
      
    - name: Build APK
      run: |
        npm install -g cordova
        cordova create myapp com.artburst.app ArtBurst
        cd myapp
        cordova platform add android
        # Create minimal HTML that redirects to your app
        echo '<html><head><meta http-equiv="refresh" content="0; url=https://terrence0909.github.io/art-burst/"></head></html>' > www/index.html
        cordova build android
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ArtBurst-APK
        path: myapp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
