name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Verify build output
      run: |
        echo "Build contents:"
        ls -la dist/
        echo "Project structure:"
        find . -name "*.tsx" -o -name "*.ts" | head -10
      
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Build APK with Cordova
      run: |
        npm install -g cordova
        cordova create temp-app com.artburst.app ArtBurst
        cd temp-app
        cordova platform add android
        
        # Copy the built React app to Cordova www folder
        echo "Copying built React app to Cordova..."
        rm -rf www/*
        cp -r ../dist/* www/
        
        # Verify the files were copied
        echo "Cordova www contents:"
        ls -la www/
        
        cordova build android
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ArtBurst-APK
        path: temp-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7
