name: Build Android APK with Custom Logo
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Create APK with ArtBurst Logo
      run: |
        npm install -g cordova
        cordova create ArtBurst-APK com.artburst.app ArtBurst
        cd ArtBurst-APK
        
        # Create a simple HTML file that redirects to your app
        echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=https://terrence0909.github.io/art-burst/"></head><body><p>Loading ArtBurst...</p></body></html>' > www/index.html
        
        # Copy your specific FULL-LOGO.png to Cordova resources
        echo "Using ArtBurst logo: src/assets/FULL-LOGO.png"
        cp ../src/assets/FULL-LOGO.png res/icon.png
        
        cordova platform add android
        cordova build android
        
        echo "✅ APK built with ArtBurst logo!"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ArtBurst-APK-With-Logo
        path: ArtBurst-APK/platforms/android/app/build/outputs/apk/debug/app-debug.apk
